---
title: "Write Up"
author: "Tony Hung"
toc: true
number-sections: true
highlight-style: pygments
date: " Last updated: `r weekdays(Sys.Date())`, `r Sys.Date()`"
format:
  html: 
    code-fold: true
    html-math-method: katex
    theme: minty
editor: visual
---

## Abstract

### Keywords

## Introduction



## Scoping Scopus (Literature Search)
The literature search started with an experimental search in March 2023. The aim of the experimental search of literature is to scout the volume and diversity of the available literature. It was evident from this experiment that there exists a colossal amount of reviews on resilience and not all reviews are equal. This experiment was helpful in further determining the exclusion and inclusion criteria and optimizing the search query as well as the steps for screening review articles. 

The Scopus search for literature was conducted on the 3rd of April 2023. There are no publication date limitations, which means that any publication published on or before 3rd of April 2023 are accepted. The review process was assisted by using Rayyan. The schematic, adapted PRISMA representation is shown in the following figure. 

The main keywords used in the query for searching on the Scopus database in titles, abstracts, and keywords were "soci\*", "commun\*", "neighbour\*", "urban", "econom\*", "financi\*", "infrastruct\*", "disast\*", "climate" and "resilience". This search query is further restricted by excluding the following keywords in the title-abstract-key: "covid", "corona", "COVID-19", "agri\*", "supply chain", "agro\*", "land", "education", "migration", "sport", "war", "coral", "farm\*" and restricted again with the following keywords in the title: "politics", "policy", "ecosystem", "forest", "worker", "governance", "river", "ecolo\*", "biodiversity", "institution\*", since it is out of scope for the paper. The document type is set to reveal review journal articles only. Obvious subject areas such as medicine, agricultural and biological sciences, psychology, biochemistry, genetics and molecular biology, computer science, neuroscience, nursing, immunology and microbiology, chemical engineering, health professions, physics and astronomy, chemistry, pharmacology, toxicology, pharmaceutics, veterinary, dentistry, arts and humanities, business, management and accounting, mathematics, and materials science are all excluded. The language of the review articles is limited to English only. Finally, the search query specifies the following keywords that should appear for inclusion: resilience, climate change,, disasters, and disaster. This search query^[( TITLE-ABS-KEY ( "soci*" OR "commun*" OR "neighbour*" OR "urban*" OR "econom*" OR "financi*" OR "infrastruct*" OR "disast*" OR "climate" ) AND TITLE-ABS-KEY ( "resilience" ) AND NOT TITLE-ABS-KEY ( "covid" OR "corona" OR "COVID-19" OR "agri*" OR "supply chain" OR "agro*" OR "land" OR "education" OR "migration" OR "sport" OR "war" OR "coral" OR "farm*" ) AND NOT TITLE ( "politics" OR "policy" OR "ecosystem" OR "forest" OR "worker" OR "governance" OR "river" OR "ecolo*" OR "biodiversity" OR "institution*" ) ) AND ( LIMIT-TO ( SRCTYPE , "j" ) ) AND ( LIMIT-TO ( DOCTYPE , "re" ) ) AND ( EXCLUDE ( SUBJAREA , "MEDI" ) OR EXCLUDE ( SUBJAREA , "AGRI" ) OR EXCLUDE ( SUBJAREA , "PSYC" ) OR EXCLUDE ( SUBJAREA , "BIOC" ) OR EXCLUDE ( SUBJAREA , "COMP" ) OR EXCLUDE ( SUBJAREA , "NEUR" ) OR EXCLUDE ( SUBJAREA , "NURS" ) OR EXCLUDE ( SUBJAREA , "IMMU" ) OR EXCLUDE ( SUBJAREA , "CENG" ) OR EXCLUDE ( SUBJAREA , "HEAL" ) OR EXCLUDE ( SUBJAREA , "PHYS" ) OR EXCLUDE ( SUBJAREA , "CHEM" ) OR EXCLUDE ( SUBJAREA , "PHAR" ) OR EXCLUDE ( SUBJAREA , "VETE" ) OR EXCLUDE ( SUBJAREA , "DENT" ) OR EXCLUDE ( SUBJAREA , "ARTS" ) OR EXCLUDE ( SUBJAREA , "BUSI" ) OR EXCLUDE ( SUBJAREA , "MATH" ) OR EXCLUDE ( SUBJAREA , "MATE" ) ) AND ( LIMIT-TO ( LANGUAGE , "English" ) ) AND ( LIMIT-TO ( EXACTKEYWORD , "Resilience" ) OR LIMIT-TO ( EXACTKEYWORD , "Climate Change" ) OR LIMIT-TO ( EXACTKEYWORD , "Disasters" ) OR LIMIT-TO ( EXACTKEYWORD , "Disaster" ) )] resulted in 446 articles in total. 

Learning from the experimental search exercise, it was difficult to determine if an article was truly a review article or not by simply scanning from the title, abstract and keywords. It was interesting to point out that even though the filter for review articles was switched on, there were still a myriad of articles that were not review articles to begin with. To further simplify the process, an additional line^[AND TITLE-ABS-KEY ( "review" OR "overview" OR "survey" )] in the search query was appended, where it only includes articles that mentions "review", "overview", or "survey" in either title, abstract, or keyword. This additional exclusion resulted in 341 articles awaiting to be screened. 

Following the screening of 341 articles, 256 articles were removed due to not being in scope with this paper. The main reasons for removing the articles was that the articles focused on sustainability, nature (such as forests or lakes), governance, health, particular species (such as beetles or plants), technology, etc. Furthering the search of 

## Results
### Resilience Definitions

